package testingforvideo;

import java.awt.Color;
import java.awt.Font;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

public class PickSuitFrame extends javax.swing.JFrame {

    private Card.Value ace = null;
    private Card chosenCard;
    private Boolean buttonClicked;
    
    
    public PickSuitFrame() {
        initComponents();
        buttonClicked = false;
        setVisible(true);
        System.out.println("initialised PICKSUITFRAME");
    }

    
    
    public Card chooseSuit(){
        return chosenCard;
    }
    
    public Boolean clickedButton() {
    	return buttonClicked;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel1.setBackground(new Color(254, 251, 234));
        jLabel1 = new javax.swing.JLabel();
        jLabel1.setBackground(new Color(254, 251, 234));
        heartButton = new javax.swing.JButton();
        diamondsButton = new javax.swing.JButton();
        spadesButton = new javax.swing.JButton();
        clubsButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("pick suit:");
        jLabel1.setToolTipText("");

        heartButton.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        heartButton.setText("hearts");
        heartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                heartButtonActionPerformed(evt);
            }
        });

        diamondsButton.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        diamondsButton.setText("diamonds");
        diamondsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diamondsButtonActionPerformed(evt);
            }
        });

        spadesButton.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        spadesButton.setText("spades");
        spadesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spadesButtonActionPerformed(evt);
            }
        });

        clubsButton.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        clubsButton.setText("clubs");
        clubsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clubsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(clubsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(heartButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(diamondsButton)
                            .addComponent(spadesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(heartButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(diamondsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(spadesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(clubsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void heartButtonActionPerformed(java.awt.event.ActionEvent evt) {                                            
        JLabel message = new JLabel("the chosen suit is hearts.");
        message.setFont(new Font("Times New Roman", Font.BOLD, 16));
        JOptionPane.showMessageDialog(null, message);
        chosenCard = new Card(Card.Suit.hearts, Card.Value.ace);
        buttonClicked = true;
        this.dispose();
        
    }                                           

    private void diamondsButtonActionPerformed(java.awt.event.ActionEvent evt) {                                               
        JLabel message = new JLabel("the chosen suit is diamonds.");
        message.setFont(new Font("Times New Roman", Font.BOLD, 16));
        JOptionPane.showMessageDialog(null, message);
        chosenCard = new Card(Card.Suit.diamonds, Card.Value.ace);
        buttonClicked = true;
        this.dispose();
        
    }                                              

    private void spadesButtonActionPerformed(java.awt.event.ActionEvent evt) {                                             
        JLabel message = new JLabel("the chosen suit is spades.");
        message.setFont(new Font("Times New Roman", Font.BOLD, 16));
        JOptionPane.showMessageDialog(null, message);
        chosenCard = new Card(Card.Suit.spades, Card.Value.ace);
        buttonClicked = true;
        this.dispose();
        
    }                                            

    private void clubsButtonActionPerformed(java.awt.event.ActionEvent evt) {                                            
        JLabel message = new JLabel("the chosen suit is clubs.");
        message.setFont(new Font("Times New Roman", Font.BOLD, 16));
        JOptionPane.showMessageDialog(null, message);
        chosenCard = new Card(Card.Suit.clubs, Card.Value.ace);
        buttonClicked = true;
        this.dispose();
        
    }                                           

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PickSuitFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PickSuitFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PickSuitFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PickSuitFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PickSuitFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton clubsButton;
    private javax.swing.JButton diamondsButton;
    private javax.swing.JButton heartButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton spadesButton;
    // End of variables declaration                   
}
